/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Moving_Characters.glb -T -j -M 
Files: raw_assets\Moving_Characters.glb [1.03MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Moving_Characters-transformed.glb [121.9KB] (88%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCurveProgressStore } from "../../store/useCurveProgressStore";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
import { AnimateMesh } from "../components/AnimateMesh";

const offsets = {
  winterFrontCharacterRef: 0.0124,
  winterSideCharacterRef: 0.0124,
  springFrontCharacterRef: 0.235,
  springSideCharacterRef: 0.235,
  summerFrontCharacterRef: 0.49,
  summerWaveRef: 0.49,
  fallFrontCharacterRef: 0.74,
};

const progressMoveRanges = {
  winter: { start: 0.02, end: 0.235 },
  spring: { start: 0.235, end: 0.49 },
  summer: { start: 0.49, end: 0.74 },
  fall: { start: 0.74, end: 0.99 },
};

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Moving_Characters-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Moving_Characters_1.webp", {
    side: "double",
  });

  const curves = useCurveProgressStore((state) => state.curves);

  const targetPosition = useRef(new THREE.Vector3(0, 0, 0));
  const targetLookAt = useRef(new THREE.Vector3(0, 0, 0));
  const upVector = useRef(new THREE.Vector3(0, 1, 0));
  const previousScrollProgress = useRef(0);

  // Consider refacotring at this point this just a bloated file XDDD

  const winterFrontCharacterRef = useRef();
  const winterSideCharacterRef = useRef();
  const springFrontCharacterRef = useRef();
  const springSideCharacterRef = useRef();
  const summerFrontCharacterRef = useRef();
  const summerWaveRef = useRef();
  const fallFrontCharacterRef = useRef();

  const winterFrontCharacterInnerWrapperRef = useRef();
  const winterSideCharacterInnerWrapperRef = useRef();
  const springFrontCharacterInnerWrapperRef = useRef();
  const springSideCharacterInnerWrapperRef = useRef();
  const summerFrontCharacterInnerWrapperRef = useRef();
  const summerWaveInnerWrapperRef = useRef();
  const fallFrontCharacterInnerWrapperRef = useRef();

  const winterLeftArmRef = useRef();
  const winterRightArmRef = useRef();
  const winterLeftFootRef = useRef();
  const winterRightFootRef = useRef();

  const springFrontWheelRef = useRef();
  const springBackWheelRef = useRef();

  const winterSideFaceRef = useRef();
  const winterSideFaceSmileRef = useRef();
  const springSideFaceRef = useRef();
  const springSideFaceSmileRef = useRef();

  const winterSideCharacterSwapRef = useRef();
  const winterFrontCharacterSwapRef = useRef();
  const springSideCharacterSwapRef = useRef();
  const springFrontCharacterSwapRef = useRef();

  const isScrolling = useRef(false);
  const scrollTimeout = useRef(null);

  const idleTimer = useRef(null);
  const winterShowingFront = useRef(true);
  const springShowingFront = useRef(true);

  useEffect(() => {
    const map = [
      [winterFrontCharacterRef, offsets.winterFrontCharacterRef],
      [winterSideCharacterRef, offsets.winterSideCharacterRef],
      [springFrontCharacterRef, offsets.springFrontCharacterRef],
      [springSideCharacterRef, offsets.springSideCharacterRef],
      [summerFrontCharacterRef, offsets.summerFrontCharacterRef],
      [summerWaveRef, offsets.summerWaveRef],
      [fallFrontCharacterRef, offsets.fallFrontCharacterRef],
    ];

    map.forEach(([ref, offset]) => {
      curves.movingCharactersCurve.getPointAt(offset, targetPosition.current);
      ref.current.position.copy(targetPosition.current);
    });
  }, [curves]);

  const visibilityStates = useRef({});

  const moveObjectOrCharacter = (
    ref,
    innerRef,
    id,
    offset,
    range,
    scrollProgress,
  ) => {
    if (!ref.current) return;
    const { start, end } = range;

    const shouldBeVisible = scrollProgress >= start && scrollProgress < end;

    if (visibilityStates.current[id] !== shouldBeVisible) {
      visibilityStates.current[id] = shouldBeVisible;
      gsap.to(innerRef.current.position, {
        y: shouldBeVisible ? 0.23 : -5,
        duration: 1.5,
        ease: "back.out(1.2)",
        overwrite: "auto",
      });
    }

    const isALoop =
      Math.abs(scrollProgress - previousScrollProgress.current) > 0.5;

    const clampedProgress = Math.min(Math.max(scrollProgress, start), end);
    const rangeProgress = (clampedProgress - start) / (end - start);
    const curveValue = offset + rangeProgress * (end - start);

    curves.movingCharactersCurve.getPointAt(curveValue, targetPosition.current);
    const tangent = curves.movingCharactersCurve.getTangentAt(curveValue);

    if (isALoop) {
      ref.current.position.copy(targetPosition.current);
    } else {
      ref.current.position.lerp(targetPosition.current, 0.1);
    }

    targetLookAt.current.crossVectors(tangent, upVector.current);
    ref.current.lookAt(targetLookAt.current);
  };

  useFrame((state) => {
    if (!curves?.movingCharactersCurve) return;

    // console.log(gsap.globalTimeline.getChildren().length);
    const scrollProgress = useCurveProgressStore.getState().scrollProgress;

    moveObjectOrCharacter(
      winterFrontCharacterRef,
      winterFrontCharacterInnerWrapperRef,
      "winterFront",
      offsets.winterFrontCharacterRef,
      progressMoveRanges.winter,
      scrollProgress,
    );
    moveObjectOrCharacter(
      winterSideCharacterRef,
      winterSideCharacterInnerWrapperRef,
      "winterSide",
      offsets.winterSideCharacterRef,
      progressMoveRanges.winter,
      scrollProgress,
    );
    moveObjectOrCharacter(
      springFrontCharacterRef,
      springFrontCharacterInnerWrapperRef,
      "springFront",
      offsets.springFrontCharacterRef,
      progressMoveRanges.spring,
      scrollProgress,
    );
    moveObjectOrCharacter(
      springSideCharacterRef,
      springSideCharacterInnerWrapperRef,
      "springSide",
      offsets.springSideCharacterRef,
      progressMoveRanges.spring,
      scrollProgress,
    );
    moveObjectOrCharacter(
      summerFrontCharacterRef,
      summerFrontCharacterInnerWrapperRef,
      "summerFront",
      offsets.summerFrontCharacterRef,
      progressMoveRanges.summer,
      scrollProgress,
    );
    moveObjectOrCharacter(
      summerWaveRef,
      summerWaveInnerWrapperRef,
      "summerWaveRef",
      offsets.summerWaveRef,
      progressMoveRanges.summer,
      scrollProgress,
    );
    moveObjectOrCharacter(
      fallFrontCharacterRef,
      fallFrontCharacterInnerWrapperRef,
      "fallFront",
      offsets.fallFrontCharacterRef,
      progressMoveRanges.fall,
      scrollProgress,
    );

    const { start, end } = progressMoveRanges.winter;
    const isVisible = scrollProgress >= start && scrollProgress < end;

    if (isVisible) {
      const wave = scrollProgress * 100;

      const armSwing = Math.sin(wave) * 0.7;
      const footSwing = Math.sin(wave) * 0.7;

      if (winterLeftArmRef.current) {
        winterLeftArmRef.current.rotation.z =
          nodes.Moving_Characters_Winter_left_arm.rotation.z + armSwing;
      }
      if (winterRightArmRef.current) {
        winterRightArmRef.current.rotation.z =
          nodes.Moving_Characters_Winter_right_arm.rotation.z - armSwing;
      }
      if (winterLeftFootRef.current) {
        winterLeftFootRef.current.rotation.z =
          nodes.Moving_Characters_Winter_left_foot.rotation.z + footSwing;
      }
      if (winterRightFootRef.current) {
        winterRightFootRef.current.rotation.z =
          nodes.Moving_Characters_Winter_right_foot.rotation.z - footSwing;
      }
    }

    const wheelSpeed = 205;
    if (springFrontWheelRef.current) {
      springFrontWheelRef.current.rotation.z =
        nodes.Moving_Characters_Spring_side_front_wheel.rotation.z -
        scrollProgress * wheelSpeed;
    }
    if (springBackWheelRef.current) {
      springBackWheelRef.current.rotation.z =
        nodes.Moving_Characters_Spring_side_back_wheel.rotation.z -
        scrollProgress * wheelSpeed;
    }

    const scrollChanged = scrollProgress !== previousScrollProgress.current;
    if (scrollChanged) {
      isScrolling.current = true;

      if (scrollTimeout.current) clearTimeout(scrollTimeout.current);
      if (idleTimer.current) clearTimeout(idleTimer.current);

      const { winter, spring } = progressMoveRanges;

      if (
        winterShowingFront.current &&
        scrollProgress >= winter.start &&
        scrollProgress < winter.end
      ) {
        winterShowingFront.current = false;
        gsap.to(winterFrontCharacterSwapRef.current.position, {
          y: -5,
          duration: 0.4,
          ease: "back.in(1.2)",
          overwrite: true,
        });
        gsap.to(winterSideCharacterSwapRef.current.position, {
          y: 0,
          duration: 0.6,
          delay: 0.2,
          ease: "back.out(1.2)",
          overwrite: true,
        });
      }
      if (
        springShowingFront.current &&
        scrollProgress >= spring.start &&
        scrollProgress < spring.end
      ) {
        springShowingFront.current = false;
        gsap.to(springFrontCharacterSwapRef.current.position, {
          y: -5,
          duration: 0.4,
          ease: "back.in(1.2)",
          overwrite: true,
        });
        gsap.to(springSideCharacterSwapRef.current.position, {
          y: 0,
          duration: 0.6,
          delay: 0.2,
          ease: "back.out(1.2)",
          overwrite: true,
        });
      }

      scrollTimeout.current = setTimeout(() => {
        isScrolling.current = false;
      }, 50);

      idleTimer.current = setTimeout(() => {
        if (!winterShowingFront.current) {
          winterShowingFront.current = true;
          gsap.to(winterSideCharacterSwapRef.current.position, {
            y: -5,
            duration: 0.4,
            ease: "back.in(1.2)",
          });
          gsap.to(winterFrontCharacterSwapRef.current.position, {
            y: 0,
            duration: 0.6,
            delay: 0.2,
            ease: "back.out(1.2)",
          });
        }
        if (!springShowingFront.current) {
          springShowingFront.current = true;
          gsap.to(springSideCharacterSwapRef.current.position, {
            y: -5,
            duration: 0.4,
            ease: "back.in(1.2)",
          });
          gsap.to(springFrontCharacterSwapRef.current.position, {
            y: 0,
            duration: 0.6,
            delay: 0.2,
            ease: "back.out(1.2)",
          });
        }
      }, 3000);
    }

    const scrolling = isScrolling.current;
    if (winterSideFaceRef.current)
      winterSideFaceRef.current.visible = !scrolling;
    if (winterSideFaceSmileRef.current)
      winterSideFaceSmileRef.current.visible = scrolling;
    if (springSideFaceRef.current)
      springSideFaceRef.current.visible = !scrolling;
    if (springSideFaceSmileRef.current)
      springSideFaceSmileRef.current.visible = scrolling;

    previousScrollProgress.current = scrollProgress;
  });

  return (
    <group {...props} dispose={null}>
      <group ref={winterFrontCharacterRef}>
        <group ref={winterFrontCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <group ref={winterFrontCharacterSwapRef} position={[0, 0, 0]}>
              <mesh
                geometry={
                  nodes.Moving_Characters_Winter_arm_left_front.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Winter_arm_left_front.position
                }
              />
              <mesh
                geometry={
                  nodes.Moving_Characters_Winter_arm_right_front.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Winter_arm_right_front.position
                }
              />
              <mesh
                geometry={
                  nodes.Moving_Characters_Winter_front_character.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Winter_front_character.position
                }
              />
              <mesh
                geometry={nodes.Moving_Characters_Winter_Front_Smile.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_Front_Smile.position}
              />
              <mesh
                geometry={
                  nodes.Moving_Characters_Winter_front_smile_face.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Winter_front_smile_face.position
                }
              />
              {/* <mesh
                geometry={nodes.Moving_Characters_Winter_happy_face.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_happy_face.position}
              /> */}
              <mesh
                geometry={nodes.Moving_Characters_Winter_head_front.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_head_front.position}
              />
            </group>
          </AnimateMesh>
        </group>
      </group>

      <group ref={winterSideCharacterRef}>
        <group ref={winterSideCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0,
              },
            ]}
          >
            <group ref={winterSideCharacterSwapRef} position={[0, -5, 0]}>
              <mesh
                ref={winterLeftArmRef}
                geometry={nodes.Moving_Characters_Winter_left_arm.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_left_arm.position}
              />
              <mesh
                ref={winterRightArmRef}
                geometry={nodes.Moving_Characters_Winter_right_arm.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_right_arm.position}
              />
              <mesh
                ref={winterLeftFootRef}
                geometry={nodes.Moving_Characters_Winter_left_foot.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_left_foot.position}
              />
              <mesh
                ref={winterRightFootRef}
                geometry={nodes.Moving_Characters_Winter_right_foot.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_right_foot.position}
              />
              <mesh
                geometry={nodes.Moving_Characters_Winter_side.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_side.position}
              />
              <mesh
                ref={winterSideFaceRef}
                geometry={nodes.Moving_Characters_Winter_side_face.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Winter_side_face.position}
              />
              <mesh
                ref={winterSideFaceSmileRef}
                geometry={
                  nodes.Moving_Characters_Winter_side_face_smile.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Winter_side_face_smile.position
                }
              />
            </group>
          </AnimateMesh>
        </group>
      </group>

      <group ref={springFrontCharacterRef}>
        <group ref={springFrontCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <group ref={springFrontCharacterSwapRef} position={[0, 0, 0]}>
              <mesh
                geometry={nodes.Moving_Characters_Spring_front.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Spring_front.position}
              />
            </group>
          </AnimateMesh>
        </group>
      </group>

      <group ref={springSideCharacterRef}>
        <group ref={springSideCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <group ref={springSideCharacterSwapRef} position={[0, -5, 0]}>
              <mesh
                geometry={nodes.Moving_Characters_Spring_side.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Spring_side.position}
                rotation={nodes.Moving_Characters_Spring_side.rotation}
                scale={nodes.Moving_Characters_Spring_side.scale}
              />
              <mesh
                ref={springBackWheelRef}
                geometry={
                  nodes.Moving_Characters_Spring_side_back_wheel.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Spring_side_back_wheel.position
                }
                rotation={
                  nodes.Moving_Characters_Spring_side_back_wheel.rotation
                }
                scale={nodes.Moving_Characters_Spring_side_back_wheel.scale}
              />
              <mesh
                ref={springFrontWheelRef}
                geometry={
                  nodes.Moving_Characters_Spring_side_front_wheel.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Spring_side_front_wheel.position
                }
                rotation={
                  nodes.Moving_Characters_Spring_side_front_wheel.rotation
                }
                scale={nodes.Moving_Characters_Spring_side_front_wheel.scale}
              />
              <mesh
                ref={springSideFaceRef}
                geometry={nodes.Moving_Characters_Spring_side_face.geometry}
                material={texture_1}
                position={nodes.Moving_Characters_Spring_side_face.position}
                scale={nodes.Moving_Characters_Spring_side_face.scale}
              />
              <mesh
                ref={springSideFaceSmileRef}
                geometry={
                  nodes.Moving_Characters_Spring_side_face_smile.geometry
                }
                material={texture_1}
                position={
                  nodes.Moving_Characters_Spring_side_face_smile.position
                }
              />
            </group>
          </AnimateMesh>
        </group>
      </group>

      <group ref={fallFrontCharacterRef}>
        <group ref={fallFrontCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <mesh
              geometry={nodes.Moving_Characters_Fall_character.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Fall_character.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Fall_face.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Fall_face.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Fall_left_arm.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Fall_left_arm.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Fall_right_arm.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Fall_right_arm.position}
            />
          </AnimateMesh>
        </group>
      </group>

      <group ref={summerWaveRef}>
        <group ref={summerWaveInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <mesh
              geometry={nodes.Moving_Characters_Summer_character_Wave.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Summer_character_Wave.position}
            />
          </AnimateMesh>
        </group>
      </group>

      <group ref={summerFrontCharacterRef}>
        <group ref={summerFrontCharacterInnerWrapperRef} position={[0, -5, 0]}>
          <AnimateMesh
            position={[0, 0, 0]}
            animations={[
              { property: "rotation", axis: "y", speed: 1, amplitude: 0.3 },
              {
                property: "position",
                axis: "y",
                speed: 2,
                amplitude: 0.05,
                base: 0.23,
              },
            ]}
          >
            <mesh
              geometry={nodes.Moving_Characters_Summer_character.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Summer_character.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Summer_happy_face.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Summer_happy_face.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Summer_left_arm.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Summer_left_arm.position}
            />
            <mesh
              geometry={nodes.Moving_Characters_Summer_right_arm.geometry}
              material={texture_1}
              position={nodes.Moving_Characters_Summer_right_arm.position}
            />
          </AnimateMesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Moving_Characters-transformed.glb");
