/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Scene_3_Summer.glb -T -j -M 
Files: raw_assets\Scene_3_Summer.glb [4.09MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_3_Summer-transformed.glb [417.36KB] (90%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { AnimateMesh } from "../components/AnimateMesh";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_3_Summer-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_3_Summer_1.webp");
  const texture_2 = useKTX2Texture("/textures/Scene_3_Summer_2.webp");
  const texture_3 = useKTX2Texture("/textures/Scene_3_Summer_3.webp");
  const texture_4 = useKTX2Texture("/textures/Scene_3_Summer_4.webp");

  const starbucksSignRef = useRef();
  const blenderSignRef = useRef();
  const figmaSignRef = useRef();
  const psychiatristSignRef = useRef();

  const FLOAT_AMOUNT = 3;
  const DURATION = 0.4;

  const createHoverHandlers = (signRef, baseY) => ({
    onPointerEnter: (e) => {
      e.stopPropagation();
      document.body.style.cursor = "pointer";
      gsap.to(signRef.current.position, {
        y: baseY + FLOAT_AMOUNT,
        duration: DURATION,
        ease: "power2.out",
      });
    },
    onPointerLeave: (e) => {
      e.stopPropagation();
      document.body.style.cursor = "auto";
      gsap.to(signRef.current.position, {
        y: baseY,
        duration: DURATION,
        ease: "power2.inOut",
      });
    },
  });

  const starbucksBaseY =
    nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.position.y - 2;
  const blenderBaseY =
    nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.position.y - 2;
  const figmaBaseY =
    nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.position.y - 2;
  const psychiatristBaseY =
    nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.position.y - 2;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_3_Summer_1.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1.position}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_Shanghai.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_Shanghai.position}
        {...createHoverHandlers(starbucksSignRef, starbucksBaseY)}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_Austin.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_Austin.position}
        {...createHoverHandlers(blenderSignRef, blenderBaseY)}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_1_Cali.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1_Cali.position}
        {...createHoverHandlers(figmaSignRef, figmaBaseY)}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_1_Boston.geometry}
        material={texture_1}
        position={nodes.Scene_3_Summer_1_Boston.position}
        {...createHoverHandlers(psychiatristSignRef, psychiatristBaseY)}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_2.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2.position}
      />

      <mesh
        ref={figmaSignRef}
        geometry={nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[
          nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.position.x,
          figmaBaseY,
          nodes.Scene_3_Summer_2_Figma_Sign_Summer_3_2.position.z,
        ]}
      />

      <mesh
        ref={psychiatristSignRef}
        geometry={nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[
          nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.position.x,
          psychiatristBaseY,
          nodes.Scene_3_Summer_2_Psychiatrist_Sign_Summer_3_2.position.z,
        ]}
      />

      <mesh
        ref={blenderSignRef}
        geometry={nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.geometry}
        material={texture_2}
        position={[
          nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.position.x,
          blenderBaseY,
          nodes.Scene_3_Summer_2_Blender_Sign_Summer_3_2.position.z,
        ]}
      />

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2.3}
        property={"scale"}
        position={nodes.Scene_3_Summer_2_seaweed.position}
        base={1.1}
        offset={2.36}
      >
        <mesh
          geometry={nodes.Scene_3_Summer_2_seaweed.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.3}
        speed={2.5}
        property={"scale"}
        position={nodes.Scene_3_Summer_2001_seaweed.position}
        base={1.1}
        offset={2.36}
      >
        <mesh
          geometry={nodes.Scene_3_Summer_2001_seaweed.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2.3}
        property={"scale"}
        position={nodes.Scene_3_Summer_2002_seaweed.position}
        base={1.1}
        offset={0.73}
      >
        <mesh
          geometry={nodes.Scene_3_Summer_2002_seaweed.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2.3}
        property={"scale"}
        position={nodes.Scene_3_Summer_2003_seaweed.position}
        base={1.1}
        offset={2.36}
      >
        <mesh
          geometry={nodes.Scene_3_Summer_2003_seaweed.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_3_Summer_2001_fish.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_fish.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_fish_two.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_fish_two.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_starfish.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_starfish.position}
      />
      <mesh
        geometry={nodes.Scene_3_Summer_2001_seahorse.geometry}
        material={texture_2}
        position={nodes.Scene_3_Summer_2001_seahorse.position}
      />

      <mesh
        geometry={nodes.Scene_3_Summer_3.geometry}
        material={texture_3}
        position={nodes.Scene_3_Summer_3.position}
      />

      <mesh
        ref={starbucksSignRef}
        geometry={nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={[
          nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.position.x,
          starbucksBaseY,
          nodes.Scene_3_Summer_4_Starbucks_Sign_Summer_3_2.position.z,
        ]}
      />

      <AnimateMesh
        axis={"y"}
        amplitude={0.05}
        speed={5}
        property={"scale"}
        position={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Crab.position}
        base={1.1}
        offset={2.36}
      >
        <mesh
          geometry={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Crab.geometry}
          material={texture_4}
        />
      </AnimateMesh>
      <mesh
        geometry={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Dragonair.geometry
        }
        material={texture_4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Dragonair.position
        }
      />
      <mesh
        geometry={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Sand_Castle_Gate.geometry
        }
        material={texture_4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2_Sand_Castle_Gate.position
        }
      />

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={4}
        position={
          nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2001_umbrella.position
        }
        base={0}
        offset={2.36}
      >
        <mesh
          geometry={
            nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2001_umbrella.geometry
          }
          material={texture_4}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2.geometry}
        material={texture_4}
        position={nodes.Scene_3_Summer_4_Bike_Sign_Summer_3_2.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_3_Summer-transformed.glb");
