/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Spring.glb -T -j -M 
Files: raw_assets\Spring.glb [1.47MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Scene_2_Spring-transformed.glb [392.27KB] (73%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { AnimateMesh } from "../components/AnimateMesh";
import { useGSAP } from "@gsap/react";
import { useCurveProgressStore } from "../../store/useCurveProgressStore";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Scene_2_Spring-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Scene_2_Spring_1.webp", {
    side: "double",
  });
  const texture_2 = useKTX2Texture("/textures/Scene_2_Spring_2.webp", {
    side: "double",
  });
  const texture_3 = useKTX2Texture("/textures/Scene_2_Spring_3.webp", {
    side: "double",
  });
  const texture_4 = useKTX2Texture("/textures/Scene_2_Spring_4.webp", {
    side: "double",
  });

  const gateLeftRef = useRef();
  const gateRightRef = useRef();
  const prevProgress = useRef(0);

  useFrame(() => {
    const curr = useCurveProgressStore.getState().scrollProgress;
    const prev = prevProgress.current;

    if (prev < 0.335 && curr >= 0.335) {
      gsap.to(gateLeftRef.current.rotation, {
        y: Math.PI / 2,
        duration: 0.6,
        ease: "power2.out",
      });
      gsap.to(gateRightRef.current.rotation, {
        y: -Math.PI / 2,
        duration: 0.6,
        ease: "power2.out",
      });
    }

    if (prev >= 0.335 && curr < 0.335) {
      gsap.to(gateLeftRef.current.rotation, {
        y: 0,
        duration: 0.6,
        ease: "power2.out",
      });
      gsap.to(gateRightRef.current.rotation, {
        y: 0,
        duration: 0.6,
        ease: "power2.out",
      });
    }

    prevProgress.current = curr;
  });

  useFrame(() => {});

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Scene_2_Spring_1_Baked.geometry}
        material={texture_1}
        position={nodes.Scene_2_Spring_1_Baked.position}
      />
      <mesh
        ref={gateRightRef}
        geometry={nodes.Scene_2_Spring_2_Gate_Right.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Gate_Right.position}
      />
      <mesh
        ref={gateLeftRef}
        geometry={nodes.Scene_2_Spring_2_Gate_Left.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Gate_Left.position}
      />
      <AnimateMesh
        axis={"z"}
        amplitude={0.2}
        speed={2}
        position={nodes.Scene_2_Spring_2_Fox_Head.position}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_2_Fox_Head.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        offset={1.75}
        position={nodes.Scene_2_Spring_2_Baked_Slime.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_2_Baked_Slime.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={0.98}
        property={"scale"}
        offset={0.12}
        position={nodes.Scene_2_Spring_2_Baked_Gnome.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_2_Baked_Gnome.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        offset={0.6}
        position={nodes.Scene_2_Spring_2_Baked_Gnome002.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_2_Baked_Gnome002.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_2_Baked_Gnome001.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_2_Baked_Gnome001.geometry}
          material={texture_2}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked_Butterfly.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked_Butterfly.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Fish.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Fish.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Outer.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Water_Outer.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_3_Water_Inner.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Water_Inner.position}
      />

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        offset={2}
        position={nodes.Scene_2_Spring_3_Baked_Duck.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Duck.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_3_Baked_Frog.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Frog.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.2}
        speed={2.2}
        position={nodes.Scene_2_Spring_3_Baked_Grass.position}
        property={"scale"}
        base={1.1}
        offset={3}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Grass.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.2}
        speed={2.2}
        position={nodes.Scene_2_Spring_3_Baked_Grass001.position}
        property={"scale"}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Grass001.geometry}
          material={texture_3}
          offset={1.5}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.2}
        speed={2.2}
        position={nodes.Scene_2_Spring_3_Baked_Grass002.position}
        property={"scale"}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Grass002.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.2}
        speed={2.2}
        position={nodes.Scene_2_Spring_3_Baked_Grass003.position}
        property={"scale"}
        offset={4.5}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Grass003.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_3_Baked_Flower.position}
        base={1.1}
        offset={0.7}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Flower.geometry}
          material={texture_3}
        />
      </AnimateMesh>
      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_3_Baked001.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked001.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_3_Baked_Flower001.position}
        base={1.1}
        offset={1.2}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Flower001.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        offset={0.5}
        position={nodes.Scene_2_Spring_3_Baked002.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked002.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        offset={0.5}
        position={nodes.Scene_2_Spring_3_Baked_Plant.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Plant.geometry}
          material={texture_3}
        />
      </AnimateMesh>
      <AnimateMesh
        axis={"y"}
        amplitude={0.1}
        speed={2}
        property={"scale"}
        position={nodes.Scene_2_Spring_3_Baked_Plant001.position}
        base={1.1}
      >
        <mesh
          geometry={nodes.Scene_2_Spring_3_Baked_Plant001.geometry}
          material={texture_3}
        />
      </AnimateMesh>

      <mesh
        geometry={nodes.Scene_2_Spring_3_Baked003.geometry}
        material={texture_3}
        position={nodes.Scene_2_Spring_3_Baked003.position}
        rotation={nodes.Scene_2_Spring_3_Baked003.rotation}
      />

      <mesh
        geometry={nodes.Scene_2_Spring_4_Baked.geometry}
        material={texture_4}
        position={nodes.Scene_2_Spring_4_Baked.position}
      />
      <mesh
        geometry={nodes.Scene_2_Spring_2_Baked.geometry}
        material={texture_2}
        position={nodes.Scene_2_Spring_2_Baked.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Scene_2_Spring-transformed.glb");
